version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch-5.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=docker-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: kibana-5.4.0
    ports:
      - "5601:5601"
    links:
      - elasticsearch
